# -*- coding: utf-8 -*-
"""ClimateNOAA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9K-BPDzItlBIPd5JAd_jE33eptqSkO7
"""

!pip install prophet plotly

import pandas as pd

# Cargar archivo local
file_path = "/mnt/FI000000304.csv"

df = pd.read_csv(file_path)

# Conversión de TMAX y TMIN a grados Celsius
df["TMAX_C"] = df["TMAX"] / 10.0
df["TMIN_C"] = df["TMIN"] / 10.0

# Calcular TAVG diario
df["TAVG_C"] = (df["TMAX_C"] + df["TMIN_C"]) / 2

# Convertir fecha
df["DATE"] = pd.to_datetime(df["DATE"])

df.head()

df.set_index("DATE", inplace=True)
monthly = df["TAVG_C"].resample("M").mean().reset_index()

monthly

from prophet import Prophet

# Prepara para Prophet
df_prophet = monthly.rename(columns={"DATE": "ds", "TAVG_C": "y"})

model = Prophet()
model.fit(df_prophet)

# Forecast 3 años (36 meses)
future = model.make_future_dataframe(periods=36, freq="M")
forecast = model.predict(future)

forecast[['ds','yhat','yhat_lower','yhat_upper']].tail()

import plotly.express as px

fig = px.line(
    forecast,
    x="ds",
    y=["yhat","yhat_lower","yhat_upper"],
    labels={"value":"TAVG (°C)", "ds":"Date"},
    title="Helsinki Monthly Average Temperature Forecast (3 years)"
)
fig.show()

import plotly.express as px

fig_hist = px.line(
    monthly,
    x="DATE",
    y="TAVG_C",
    title="Helsinki - Monthly Average Temperature (1951–2025)",
    labels={"DATE": "Date", "TAVG_C": "TAVG (°C)"}
)

# Para poder hacer zoom desde la propia gráfica
fig_hist.update_xaxes(rangeslider_visible=True)

fig_hist.show()

# df_prophet y forecast ya los tienes de antes:
# df_prophet = monthly.rename(columns={"DATE": "ds", "TAVG_C": "y"})
# model = Prophet(); model.fit(df_prophet)
# future = model.make_future_dataframe(periods=36, freq="M")
# forecast = model.predict(future)

# Parte histórica (datos observados)
hist = df_prophet.copy()

# Parte de forecast (solo fechas posteriores al último dato real)
last_real_date = hist["ds"].max()
pred = forecast[forecast["ds"] > last_real_date]

import plotly.graph_objects as go

fig = go.Figure()

# Serie histórica
fig.add_trace(go.Scatter(
    x=hist["ds"],
    y=hist["y"],
    mode="lines",
    name="Historical TAVG"
))

# Predicción central
fig.add_trace(go.Scatter(
    x=pred["ds"],
    y=pred["yhat"],
    mode="lines",
    name="AI Forecast (yhat)",
    line=dict(color="red")
))

# Banda de incertidumbre (opcional, sencillo)
fig.add_trace(go.Scatter(
    x=list(pred["ds"]) + list(pred["ds"][::-1]),
    y=list(pred["yhat_upper"]) + list(pred["yhat_lower"][::-1]),
    fill="toself",
    fillcolor="rgba(255, 0, 0, 0.2)",
    line=dict(color="rgba(255,255,255,0)"),
    hoverinfo="skip",
    showlegend=True,
    name="Forecast interval"
))

fig.update_layout(
    title="Helsinki - Historical vs AI Forecast (Monthly TAVG)",
    xaxis_title="Date",
    yaxis_title="TAVG (°C)"
)

fig.show()



file_path2 = "/mnt/DA000030380.csv"
df2 = pd.read_csv(file_path2)

df2["TMAX_C"] = df2["TMAX"] / 10.0
df2["TMIN_C"] = df2["TMIN"] / 10.0
df2["TAVG_C"] = (df2["TMAX_C"] + df2["TMIN_C"]) / 2

df2["DATE"] = pd.to_datetime(df2["DATE"])
df2 = df2.set_index("DATE")
monthly2 = df2["TAVG_C"].resample("M").mean().reset_index()

import plotly.express as px

fig = px.line()

fig.add_scatter(x=monthly["DATE"], y=monthly["TAVG_C"],
               mode="lines", name="Helsinki")

fig.add_scatter(x=monthly2["DATE"], y=monthly2["TAVG_C"],
               mode="lines", name="Copenhagen")

fig.update_layout(
    title="Monthly TAVG: Helsinki vs Copenhagen (1950–2025)",
    xaxis_title="Date",
    yaxis_title="TAVG (°C)",
)

fig.show()

df_prophet2 = monthly2.rename(columns={"DATE": "ds", "TAVG_C": "y"})
model2 = Prophet()
model2.fit(df_prophet2)
future2 = model2.make_future_dataframe(periods=36, freq="M")
forecast2 = model2.predict(future2)

last_real = df_prophet2["ds"].max()
pred2 = forecast2[forecast2["ds"] > last_real]

fig = go.Figure()

# Helsinki IA
fig.add_trace(go.Scatter(
    x=pred["ds"], y=pred["yhat"],
    mode="lines", name="Forecast Helsinki", line=dict(color="red")
))

# Copenhagen IA
fig.add_trace(go.Scatter(
    x=pred2["ds"], y=pred2["yhat"],
    mode="lines", name="Forecast Copenhagen", line=dict(color="blue")
))

fig.update_layout(
    title="AI Forecast (Prophet) — Helsinki vs Copenhagen (3 years ahead)",
    xaxis_title="Date",
    yaxis_title="Forecast TAVG (°C)"
)

fig.show()

from prophet import Prophet

# --- Helsinki ---
df_prophet = monthly.rename(columns={"DATE": "ds", "TAVG_C": "y"})
model = Prophet()
model.fit(df_prophet)
future = model.make_future_dataframe(periods=36, freq="M")
forecast = model.predict(future)

last_real_date = df_prophet["ds"].max()
hist = df_prophet.copy()
pred = forecast[forecast["ds"] > last_real_date]

# --- Copenhagen ---
df_prophet2 = monthly2.rename(columns={"DATE": "ds", "TAVG_C": "y"})
model2 = Prophet()
model2.fit(df_prophet2)
future2 = model2.make_future_dataframe(periods=36, freq="M")
forecast2 = model2.predict(future2)

last_real_date2 = df_prophet2["ds"].max()
hist2 = df_prophet2.copy()
pred2 = forecast2[forecast2["ds"] > last_real_date2]

import plotly.graph_objects as go

fig = go.Figure()

# 0 - Helsinki histórico
fig.add_trace(go.Scatter(
    x=hist["ds"],
    y=hist["y"],
    mode="lines",
    name="Helsinki - Historical",
))

# 1 - Helsinki forecast
fig.add_trace(go.Scatter(
    x=pred["ds"],
    y=pred["yhat"],
    mode="lines",
    name="Helsinki - Forecast",
    line=dict(dash="dash")
))

# 2 - Copenhagen histórico
fig.add_trace(go.Scatter(
    x=hist2["ds"],
    y=hist2["y"],
    mode="lines",
    name="Copenhagen - Historical",
    visible=False  # oculto al inicio
))

# 3 - Copenhagen forecast
fig.add_trace(go.Scatter(
    x=pred2["ds"],
    y=pred2["yhat"],
    mode="lines",
    name="Copenhagen - Forecast",
    line=dict(dash="dash"),
    visible=False  # oculto al inicio
))

fig.update_layout(
    title="Monthly TAVG + AI Forecast (Switch Helsinki / Copenhagen)",
    xaxis_title="Date",
    yaxis_title="TAVG (°C)",
)

# --- aquí viene el "switch" ---
fig.update_layout(
    updatemenus=[
        dict(
            type="buttons",
            direction="left",
            x=0.5, y=1.15,
            xanchor="center",
            buttons=[
                dict(
                    label="Helsinki",
                    method="update",
                    args=[
                        {"visible": [True, True, False, False]},
                        {"title": "Helsinki - Historical + AI Forecast"}
                    ],
                ),
                dict(
                    label="Copenhagen",
                    method="update",
                    args=[
                        {"visible": [False, False, True, True]},
                        {"title": "Copenhagen - Historical + AI Forecast"}
                    ],
                ),
                dict(
                    label="Both",
                    method="update",
                    args=[
                        {"visible": [True, True, True, True]},
                        {"title": "Helsinki & Copenhagen - Historical + AI Forecast"}
                    ],
                ),
            ],
        )
    ]
)

fig.show()